typography_spectrum: 0.21713537373580039
color:
  brandStrength: 0.021929839625954628
  lightness: 0.4013972554821521
  saturation: 0.9315464494284242
  rhythmicContrast: 0.6650838698260486
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.44243743107654154
author:
  name: Patricia Burgess
  email: patricia@berkllc.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d5463a7f-b45a-4f30-a6ea-90ebf1789912.jpg
name: Supply Butterfly
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/25a6c283-5480-40de-b671-2fbd4e3d1d98.png
title: '...it''s the little things '
